Import('env')

preinstall = [['scrollkeeper-preinstall', '$prefix/share/sampler/doc/sampler-guide/C/sampler-guide.xml', '$SOURCE', '$TARGET']]
Default(env.Command('sampler-guide-C.omf.out', 'sampler-guide-C.omf', preinstall))

sections = [ 'ar01s0%d.html' % secnum for secnum in xrange(2, 6) ]
html = env.Command(['index.html'] + sections, 'sampler-guide.xml',
                   [['xsltproc', '--stringparam', 'base.dir', '$TARGET.dir/', '$SOURCE']])
Alias('html', html)

Alias('test', map(env.TestXML, [
    ['sampler-guide.xml', '#doc/config.xml'],
    'sampler-guide-C.omf',
    ]))
