#!/bin/sh -e

cd "`dirname $0`"

#./sync-from-www

#backup=$HOME/research
#tar cf - sampler-uploads | gpg --encrypt --recipient=liblit >$backup/sampler-uploads.tar.gpg

find sampler-uploads -maxdepth 1 | { read; cat; } | ./insert-runs.pl "$@"

touch sync-stamp
