#!/usr/bin/python

try:
    import imp
    fp, pathname, description = imp.find_module('egg')
    egg = imp.load_module('egg', fp, pathname, description)
    imp.find_module('trayicon', egg.__path__)

except ImportError:
    import sys
    sys.exit(1)
