Import('env')

subproject = Dir('llvm-instrumentation-driver')
baseDriver = subproject.File('driver.py')

tenv = env.Clone()
tenv.AppendENVPath('PYTHONPATH', subproject.abspath)
pythons = (baseDriver, 'samplerDriver.py')
test = tenv.TestPython('pychecker.passed', pythons)
Alias('test', test)
