#!/usr/bin/python -O

import sys
sys.path.append('../common')

import Paths
Paths.home = '.'
Paths.ui = './preferences.ui'

from os.path import dirname, realpath
import SamplerConfig
SamplerConfig.pixmapsdir = dirname(realpath(sys.argv[0])) + '/../pixmaps'

import Main
Main.main()
