from glob import glob

SConscript(dirs='cfg')

Import('env')
env = env.Copy(LEXFLAGS=['-f', '-p'], LIBS='fl', OCAML_LIBS=['unix', 'str'])
env.AppendUnique(OCAML_PATH=['tools', 'ocaml'])

wenv = env.Copy()
wenv.AppendUnique(CCFLAGS=['-Wno-sign-compare'])
wenv.ParseConfig('gsl-config --cflags --libs')
Default(wenv.Program('decimate-samples.l'))

env.OcamlObject(glob('*.ml') + glob('*.mli'))
Default(env.OcamlProgram('resolve-samples.ml'),
        env.OcamlProgram('resolve-timestamps.ml'))

# wrapper.in
# sampler.mk
