#!/usr/bin/perl -w

use strict;

use FileHandle;


########################################################################


my @libraries = ('/usr/lib/libc_nonshared.a',
		 '-D /lib/libc.so.6',
		 '-D /lib/libm.so.6');

my %funcs;


foreach my $library (@libraries) {
    my $nm = new FileHandle "nm --defined-only -g -p $library |";
    while ($_ = $nm->getline) {
	chomp;
	my (undef, $kind, $name) = split;
	next unless defined $kind;
	next unless $kind eq 'T' || $kind eq 'W';
	next if $name eq 'bsearch';
	next if $name eq 'qsort';
	next if $name =~ /setjmp/;
	next if $name =~ /longjmp/;
	$funcs{$name} = 1;
    }
}


########################################################################


my $template = new FileHandle 'libraries.ml.in';

while (<$template>) {
    if ($_ =~ /^(\s*)\(\* \@LIBRARY_FUNCTIONS\@ \*\)$/) {
	print "$1\"$_\";\n" while $_ = each %funcs;
    } else {
	print $_;
    }
}
