#!/usr/bin/perl -w

use strict;


sub print_interface ($@) {
    my $target = shift;
    # interface recompile
    print "$target.cmi:";
    print " $_.cmi" foreach @_;
    print "\n";
}


while (<>) {
    my $line;
    my $long;

    do {
	chomp;
	$long = s/\\$//;
	$line .= $_;
	$_ = <> if $long;
    } while $long;

    $_ = $line;
    my @F = split;
    
    my $target = shift @F;
    next unless $target =~ s/(.*)\.cm([io]):/$1/;
    my $implementation = $2 eq 'o';
    (s/^(.*)\.cm[io]$/$1/ or die) foreach @F;

    if ($implementation) {
	# implementation recompile
	print "${target}.\$(cmo):";
	print " $_.cmi" foreach @F;
	print "\n";

	if (-e "$target.mli") {
	    pop @F;
	} else {
	    # implicit interface recompile
	    print_interface $target, @F;
	}

	# implementation link order
	my $clean = $target;
	print "$target =";
	print " \$($_)" foreach @F;
	print " $target.\$(cmo)\n";
    } else {
	# explicit interface recompile
	print_interface $target, @F;
    }
}
