import sys

Import('env')
env = env.Copy()
env.AppendUnique(CPPPATH=['%s/include/python%s' % (sys.prefix, sys.version[:3])])
env.ParseConfig('pkg-config --cflags --libs libbonobo-2.0 pygobject-2.0')
# todo: if above fails, try PKG_CHECK_MODULES(MONITOR, libbonobo-2.0 pygtk-2.0, , gnome_ok=no)

wenv = env.Copy()
wenv.AppendUnique(CCFLAGS=['-Wno-missing-field-initializers'])

defs = env.Command('monitor.defs', 'monitor.h', 'python /usr/share/pygtk/2.0/codegen/h2def.py $SOURCES >$TARGET')
wrap = env.Command('monitor-wrap.c', ['monitor.override', defs], 'pygtk-codegen-2.0 --prefix monitor --override $SOURCES >$TARGET')
mod = env.SharedObject('monitor-module.c')
lib = wenv.SharedLibrary('monitor', ['monitor.c', wrap, mod], SHLIBPREFIX='')
Default(lib)
