Import('env')
env = env.Copy()
env.AppendUnique(CCFLAGS=['--sampler-scheme=bounds', '--assign-across-pointer'])

Alias('test:bounds', env.Expect([
    env.CBIResolvedSamples('enum.c'),
    ]))

Alias('test', 'test:bounds')
