#!/usr/bin/python

from os.path import dirname, realpath
import sys

home = realpath(dirname(sys.argv[0]))
sys.path.append(home)
import Paths
Paths.home = home
Paths.glade = home + '/first-time.glade'

sys.path.append(realpath(home + '../common'))
import SamplerConfig
SamplerConfig.pixmapsdir = realpath(home + '../pixmaps')


import Main
