Import('env')

penv = env.Copy()
penv.AppendUnique(CC=['-pipe'])

senv = env.Copy(SHLIBPREFIX='')
plugin = senv.CBISharedLibrary('libplugin.so', 'plugin.c')
library = senv.CBISharedLibrary('library.c')
main = senv.CBIProgram(['main.c', library], LIBS='dl')

Alias('test:nothing', [
    penv.CBIResolvedCFG('pipes.c', objects='pipes'),
    env.CBIStaticObject('last-switch.c'),
    env.Expect(env.CBIResolvedCFG('cfg.c', objects='cfg')),
    senv.CBIReports([main, plugin]),
    ])

Alias('test', 'test:nothing')
