/* Generated by CIL v. 1.0 */

# 5 "/var/local/liblit/ocaml/sampler/libcountdown/countdown.h"
extern unsigned int nextLogCountdown ;
# 8
extern unsigned int resetCountdown() ;
# 7 "/var/local/liblit/ocaml/sampler/liblog/log.h"
extern void logTableau(void const   * , unsigned int  ) ;
# 6 "array.c"
struct _loggerTableau2 {
   char const   file[8] ;
   unsigned int const   line ;
   char const   expr_1[6] ;
   char const   type_1 ;
   int value_1 ;
   char const   expr_0[14] ;
   char const   type_0 ;
   int value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 6
static struct _loggerTableau2 _loggerTableau2  = 
# 6
     {"array.c", 6U, "index", 4, 0, "values[index]", 4, 0, 0};
# 5
struct _loggerTableau1 {
   char const   file[8] ;
   unsigned int const   line ;
   char const   expr_0[10] ;
   char const   type_0 ;
   int value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 5
static struct _loggerTableau1 _loggerTableau1  =    {"array.c", 5U, "values[3]", 4, 0, 0};
# 11
int main(void) 
{ int values[5] ;
  int index ;
  int direct ;
  int indirect ;
  unsigned int localCountdown6 ;

  {
  localCountdown6 = nextLogCountdown;
  if (__builtin_expect(localCountdown6 > 2U, 1)) {
    {
# 3
    values[0] = 1;
# 3
    values[1] = 2;
# 3
    values[2] = 3;
# 3
    values[3] = 4;
# 3
    values[4] = 5;
# 4
    index = 2;
    {
# 5
    localCountdown6 --;
# 5
    direct = values[3];
    }
    {
# 6
    localCountdown6 --;
# 6
    indirect = values[index];
    }
    }
    {
# 8
    nextLogCountdown = localCountdown6;
# 8
    return (0);
    }
  } else {
    {
# 3
    values[0] = 1;
# 3
    values[1] = 2;
# 3
    values[2] = 3;
# 3
    values[3] = 4;
# 3
    values[4] = 5;
# 4
    index = 2;
    {
# 5
    localCountdown6 --;
# 5
    if (localCountdown6 == 0) {
# 5
      localCountdown6 = resetCountdown();
# 5
      _loggerTableau1.value_0 = values[3];
# 5
      logTableau(& _loggerTableau1, sizeof(struct _loggerTableau1 ));
    }
# 5
    direct = values[3];
    }
    {
# 6
    localCountdown6 --;
# 6
    if (localCountdown6 == 0) {
# 6
      localCountdown6 = resetCountdown();
# 6
      _loggerTableau2.value_1 = index;
# 6
      _loggerTableau2.value_0 = values[index];
# 6
      logTableau(& _loggerTableau2, sizeof(struct _loggerTableau2 ));
    }
# 6
    indirect = values[index];
    }
    }
    {
# 8
    nextLogCountdown = localCountdown6;
# 8
    return (0);
    }
  }
}
}
