/* Generated by CIL v. 1.0 */

# 5 "/var/local/liblit/ocaml/sampler/libcountdown/countdown.h"
extern unsigned int nextLogCountdown ;
# 8
extern unsigned int resetCountdown() ;
# 7 "/var/local/liblit/ocaml/sampler/liblog/log.h"
extern void logTableau(void const   * , unsigned int  ) ;
# 75 "/usr/include/ctype.h"
extern unsigned short const   *__ctype_b ;
# 12 "bumpy.c"
struct _loggerTableau3 {
   char const   file[8] ;
   unsigned int const   line ;
   char const   expr_0[7] ;
   char const   type_0 ;
   unsigned int value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 12
static struct _loggerTableau3 _loggerTableau3  =    {"bumpy.c", 12U, "digits", 5, 0U, 0};
# 11
struct _loggerTableau2 {
   char const   file[8] ;
   unsigned int const   line ;
   char const   expr_0[4] ;
   char const   type_0 ;
   void const   *value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 11
static struct _loggerTableau2 _loggerTableau2  =    {"bumpy.c", 11U, "ptr", 15, (void const   *)0, 0};
# 9
struct _loggerTableau1 {
   char const   file[8] ;
   unsigned int const   line ;
   char const   expr_3[10] ;
   char const   type_3 ;
   void const   *value_3 ;
   char const   expr_2[4] ;
   char const   type_2 ;
   void const   *value_2 ;
   char const   expr_1[7] ;
   char const   type_1 ;
   char value_1 ;
   char const   expr_0[30] ;
   char const   type_0 ;
   unsigned short value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 9
static struct _loggerTableau1 _loggerTableau1  = 
# 9
     {"bumpy.c", 9U, "__ctype_b", 15, (void const   *)0, "ptr", 15, (void const   *)0,
    "(*ptr)", 1, 0, "(*(__ctype_b + (int )(*ptr)))", 7, 0, 0};
# 4
int main(void) 
{ char *ptr ;
  unsigned int digits ;
  unsigned int localCountdown4 ;

  {
  localCountdown4 = nextLogCountdown;
  if (__builtin_expect(localCountdown4 > 3U, 1)) {
    {
# 6
    ptr = "123abc";
# 7
    digits = 0U;
    }
    {
    {
    while_0_continue: /* CIL Label */ ;
    {
# 9
    localCountdown4 --;
# 9
    if (! ((int const   )(*(__ctype_b + (int )(*ptr))) & 2048)) {
      goto while_0_break;
    }
    }
    {
    {
# 11
    localCountdown4 --;
# 11
    ptr ++;
    }
    {
# 12
    localCountdown4 --;
# 12
    digits ++;
    }
    }
# 9
    if (__builtin_expect(localCountdown4 > 3U, 1)) {
      goto while_0_continue;
    } else {
      goto while_0_continue__dup;
    }
    }
    while_0_break: /* CIL Label */ ;
    }
    {
# 15
    nextLogCountdown = localCountdown4;
# 15
    return (0);
    }
  } else {
    {
# 6
    ptr = "123abc";
# 7
    digits = 0U;
    }
    {
    {
    while_0_continue__dup: /* CIL Label */ ;
    {
# 9
    localCountdown4 --;
# 9
    if (localCountdown4 == 0) {
# 9
      localCountdown4 = resetCountdown();
# 9
      _loggerTableau1.value_3 = (void const   *)__ctype_b;
# 9
      _loggerTableau1.value_2 = (void const   *)ptr;
# 9
      _loggerTableau1.value_1 = (*ptr);
# 9
      _loggerTableau1.value_0 = (*(__ctype_b + (int )(*ptr)));
# 9
      logTableau(& _loggerTableau1, sizeof(struct _loggerTableau1 ));
    }
# 9
    if (! ((int const   )(*(__ctype_b + (int )(*ptr))) & 2048)) {
      goto while_0_break__dup;
    }
    }
    {
    {
# 11
    localCountdown4 --;
# 11
    if (localCountdown4 == 0) {
# 11
      localCountdown4 = resetCountdown();
# 11
      _loggerTableau2.value_0 = (void const   *)ptr;
# 11
      logTableau(& _loggerTableau2, sizeof(struct _loggerTableau2 ));
    }
# 11
    ptr ++;
    }
    {
# 12
    localCountdown4 --;
# 12
    if (localCountdown4 == 0) {
# 12
      localCountdown4 = resetCountdown();
# 12
      _loggerTableau3.value_0 = digits;
# 12
      logTableau(& _loggerTableau3, sizeof(struct _loggerTableau3 ));
    }
# 12
    digits ++;
    }
    }
# 9
    if (__builtin_expect(localCountdown4 > 3U, 1)) {
      goto while_0_continue;
    } else {
      goto while_0_continue__dup;
    }
    }
    while_0_break__dup: /* CIL Label */ ;
    }
    {
# 15
    nextLogCountdown = localCountdown4;
# 15
    return (0);
    }
  }
}
}
