/* Generated by CIL v. 1.0 */

# 5 "/var/local/liblit/ocaml/sampler/libcountdown/countdown.h"
extern unsigned int nextLogCountdown ;
# 8
extern unsigned int resetCountdown() ;
# 7 "/var/local/liblit/ocaml/sampler/liblog/log.h"
extern void logTableau(void const   * , unsigned int  ) ;
# 6 "conditional.c"
struct _loggerTableau1 {
   char const   file[14] ;
   unsigned int const   line ;
   char const   expr_0[10] ;
   char const   type_0 ;
   int value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 6
static struct _loggerTableau1 _loggerTableau1  =    {"conditional.c", 6U, "predicate", 4, 0, 0};
# 11
int main(void) 
{ int predicate ;
  int result ;
  unsigned int localCountdown4 ;

  {
  localCountdown4 = nextLogCountdown;
  if (__builtin_expect(localCountdown4 > 1U, 1)) {
    {
# 3
    predicate = 19;
# 4
    result = 3;
    }
    {
# 6
    localCountdown4 --;
# 6
    if (predicate) {
# 6
      result = 0;
    }
    }
    {
# 9
    nextLogCountdown = localCountdown4;
# 9
    return (0);
    }
  } else {
    {
# 3
    predicate = 19;
# 4
    result = 3;
    }
    {
# 6
    localCountdown4 --;
# 6
    if (localCountdown4 == 0) {
# 6
      localCountdown4 = resetCountdown();
# 6
      _loggerTableau1.value_0 = predicate;
# 6
      logTableau(& _loggerTableau1, sizeof(struct _loggerTableau1 ));
    }
# 6
    if (predicate) {
# 6
      result = 0;
    }
    }
    {
# 9
    nextLogCountdown = localCountdown4;
# 9
    return (0);
    }
  }
}
}
