/* Generated by CIL v. 1.0 */

# 5 "/var/local/liblit/ocaml/sampler/libcountdown/countdown.h"
extern unsigned int nextLogCountdown ;
# 8
extern unsigned int resetCountdown() ;
# 7 "/var/local/liblit/ocaml/sampler/liblog/log.h"
extern void logTableau(void const   * , unsigned int  ) ;
# 8 "deep-pointers.c"
struct _loggerTableau1 {
   char const   file[16] ;
   unsigned int const   line ;
   char const   expr_3[3] ;
   char const   type_3 ;
   void const   *value_3 ;
   char const   expr_2[6] ;
   char const   type_2 ;
   void const   *value_2 ;
   char const   expr_1[11] ;
   char const   type_1 ;
   void const   *value_1 ;
   char const   expr_0[16] ;
   char const   type_0 ;
   void const   *value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 8
static struct _loggerTableau1 _loggerTableau1  = 
# 8
     {"deep-pointers.c", 8U, "v4", 15, (void const   *)0, "(*v4)", 15, (void const   *)0,
    "(*((*v4)))", 15, (void const   *)0, "(*((*((*v4)))))", 15, (void const   *)0,
    0};
# 11
int main(void) 
{ int v0 ;
  int *v1 ;
  int **v2 ;
  int ***v3 ;
  int ****v4 ;
  unsigned int localCountdown7 ;

  {
  localCountdown7 = nextLogCountdown;
  if (__builtin_expect(localCountdown7 > 1U, 1)) {
    {
# 4
    v1 = & v0;
# 5
    v2 = & v1;
# 6
    v3 = & v2;
# 7
    v4 = & v3;
    {
# 8
    localCountdown7 --;
# 8
    (*((*((*((*v4))))))) = 14;
    }
    }
    {
# 10
    nextLogCountdown = localCountdown7;
# 10
    return (0);
    }
  } else {
    {
# 4
    v1 = & v0;
# 5
    v2 = & v1;
# 6
    v3 = & v2;
# 7
    v4 = & v3;
    {
# 8
    localCountdown7 --;
# 8
    if (localCountdown7 == 0) {
# 8
      localCountdown7 = resetCountdown();
# 8
      _loggerTableau1.value_3 = (void const   *)v4;
# 8
      _loggerTableau1.value_2 = (void const   *)(*v4);
# 8
      _loggerTableau1.value_1 = (void const   *)(*((*v4)));
# 8
      _loggerTableau1.value_0 = (void const   *)(*((*((*v4)))));
# 8
      logTableau(& _loggerTableau1, sizeof(struct _loggerTableau1 ));
    }
# 8
    (*((*((*((*v4))))))) = 14;
    }
    }
    {
# 10
    nextLogCountdown = localCountdown7;
# 10
    return (0);
    }
  }
}
}
