/* Generated by CIL v. 1.0 */

# 5 "/var/local/liblit/ocaml/sampler/libcountdown/countdown.h"
extern unsigned int nextLogCountdown ;
# 8
extern unsigned int resetCountdown() ;
# 7 "/var/local/liblit/ocaml/sampler/liblog/log.h"
extern void logTableau(void const   * , unsigned int  ) ;
# 5 "loop.c"
struct _loggerTableau3 {
   char const   file[7] ;
   unsigned int const   line ;
   char const   expr_0[11] ;
   char const   type_0 ;
   int value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 5
static struct _loggerTableau3 _loggerTableau3  =    {"loop.c", 5U, "iterations", 4, 0, 0};
# 5
struct _loggerTableau2 {
   char const   file[7] ;
   unsigned int const   line ;
   char const   expr_0[4] ;
   char const   type_0 ;
   int value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 5
static struct _loggerTableau2 _loggerTableau2  =    {"loop.c", 5U, "tmp", 4, 0, 0};
# 5
struct _loggerTableau1 {
   char const   file[7] ;
   unsigned int const   line ;
   char const   expr_0[11] ;
   char const   type_0 ;
   int value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 5
static struct _loggerTableau1 _loggerTableau1  =    {"loop.c", 5U, "iterations", 4, 0, 0};
# 11
int main(void) 
{ int iterations ;
  int tmp ;
  unsigned int localCountdown4 ;

  {
  localCountdown4 = nextLogCountdown;
  if (__builtin_expect(localCountdown4 > 3U, 1)) {
# 3
    iterations = 4;
    {
    {
    while_0_continue: /* CIL Label */ ;
    {
    {
# 5
    localCountdown4 --;
# 5
    tmp = iterations;
    }
    {
# 5
    localCountdown4 --;
# 5
    iterations --;
    }
    }
    {
# 5
    localCountdown4 --;
# 5
    if (! tmp) {
      goto while_0_break;
    }
    }
# 5
    if (__builtin_expect(localCountdown4 > 3U, 1)) {
      goto while_0_continue;
    } else {
      goto while_0_continue__dup;
    }
    }
    while_0_break: /* CIL Label */ ;
    }
    {
# 8
    nextLogCountdown = localCountdown4;
# 8
    return (0);
    }
  } else {
# 3
    iterations = 4;
    {
    {
    while_0_continue__dup: /* CIL Label */ ;
    {
    {
# 5
    localCountdown4 --;
# 5
    if (localCountdown4 == 0) {
# 5
      localCountdown4 = resetCountdown();
# 5
      _loggerTableau3.value_0 = iterations;
# 5
      logTableau(& _loggerTableau3, sizeof(struct _loggerTableau3 ));
    }
# 5
    tmp = iterations;
    }
    {
# 5
    localCountdown4 --;
# 5
    if (localCountdown4 == 0) {
# 5
      localCountdown4 = resetCountdown();
# 5
      _loggerTableau1.value_0 = iterations;
# 5
      logTableau(& _loggerTableau1, sizeof(struct _loggerTableau1 ));
    }
# 5
    iterations --;
    }
    }
    {
# 5
    localCountdown4 --;
# 5
    if (localCountdown4 == 0) {
# 5
      localCountdown4 = resetCountdown();
# 5
      _loggerTableau2.value_0 = tmp;
# 5
      logTableau(& _loggerTableau2, sizeof(struct _loggerTableau2 ));
    }
# 5
    if (! tmp) {
      goto while_0_break__dup;
    }
    }
# 5
    if (__builtin_expect(localCountdown4 > 3U, 1)) {
      goto while_0_continue;
    } else {
      goto while_0_continue__dup;
    }
    }
    while_0_break__dup: /* CIL Label */ ;
    }
    {
# 8
    nextLogCountdown = localCountdown4;
# 8
    return (0);
    }
  }
}
}
