/* Generated by CIL v. 1.0 */

# 5 "/var/local/liblit/ocaml/sampler/libcountdown/countdown.h"
extern unsigned int nextLogCountdown ;
# 8
extern unsigned int resetCountdown() ;
# 7 "/var/local/liblit/ocaml/sampler/liblog/log.h"
extern void logTableau(void const   * , unsigned int  ) ;
# 4 "return.c"
struct _loggerTableau1 {
   char const   file[9] ;
   unsigned int const   line ;
   char const   expr_0[7] ;
   char const   type_0 ;
   int value_0 ;
   char const   end ;
} __attribute__((__packed__)) ;
# 4
static struct _loggerTableau1 _loggerTableau1  =    {"return.c", 4U, "result", 4, 0, 0};
# 11
int main(void) 
{ int result ;
  unsigned int localCountdown3 ;

  {
  localCountdown3 = nextLogCountdown;
  if (__builtin_expect(localCountdown3 > 1U, 1)) {
# 3
    result = 0;
    {
# 4
    localCountdown3 --;
    {
# 4
    nextLogCountdown = localCountdown3;
# 4
    return (result);
    }
    }
  } else {
# 3
    result = 0;
    {
# 4
    localCountdown3 --;
# 4
    if (localCountdown3 == 0) {
# 4
      localCountdown3 = resetCountdown();
# 4
      _loggerTableau1.value_0 = result;
# 4
      logTableau(& _loggerTableau1, sizeof(struct _loggerTableau1 ));
    }
    {
# 4
    nextLogCountdown = localCountdown3;
# 4
    return (result);
    }
    }
  }
}
}
