Import('env')
env = env.Clone()
env.AppendUnique(CC=['-fsampler-scheme=returns'], CCFLAGS=['-fbalance-paths'])

File('work.h')

Alias('test:balance', map(env.CBIStaticObject, [
    'default.c',
    'goto-bottom.c',
    'goto-middle.c',
    'goto-top-post.c',
    'goto-top-pre.c',
    'if-both.c',
    'if-else.c',
    'if-then.c',
    'no-default.c',
    'switch-if.c',
    'loop-if.c',
    ]))

Alias('test', 'test:balance')
