language: c
addons:
  apt:
    sources:
    - avsm
    packages:
    - aspcud
    - docbook-xsl
    - flex
    - gir1.2-webkit-3.0
    - inkscape
    - libdbus-1-dev
    - libglib2.0-dev
    - libgsl0-dev
    - liblttng-ust-dev
    - ocaml-native-compilers
    - opam
before_install:
- opam init --yes
- opam install --yes cil
install: scons OCAML_NATIVE=$OCAML_NATIVE
script: scons test
before_cache: rm --force --recursive $HOME/.opam/log
cache:
  directories:
  - "$HOME/.opam"
env:
  matrix:
  - OCAML_NATIVE=yes
  - OCAML_NATIVE=no
