#!/bin/sh -x

dir=`dirname $0`
make -C $dir main

src=/var/local/liblit/downloads/gimp-1.2.3/pp
# find $src -name '*.i' -print0 | xargs -0 -r -t $dir/main
find $src -name '*.i' -print | while read name; do $dir/main $name; done
