#!/usr/bin/perl -w

use strict;

while (<>) {
    my $line;
    my $long;

    do {
	chomp;
	$long = s/\\$//;
	$line .= $_;
	$_ = <> if $long;
    } while $long;

    $_ = $line;
    my @F = split;

    my @deps = @F;
    s/\.cm[ox]$/\.cmi/ foreach @deps[1 .. $#F];
    print "@deps\n";
    
    print "@deps\n" if $deps[0] =~ s/(.*)\.cmo:$/$1.cmi:/ && ! -e "$1.mli";

    if ($F[0] =~ s/\.cm([io]):$/.d$1:/) {
	foreach (@F[1 .. $#F]) {
	    s/\.cmi$/.mli/;
	    s/\.cmo$/.ml/;
	}
	print "@F\n";
	print "@F[1 .. $#F]:\n";
    }
}
