#!/usr/bin/perl -w

use strict;
use File::Basename;
use File::Temp qw(tmpnam);
use FindBin;


########################################################################


sub sys (@) {
    system @_;
}


my $compiler = shift;
my @cpp = ($compiler);
my @cc = ($compiler);
my @source;

my $linking = 1;


while ($_ = shift) {
    if (/^-/) {
	if (/^-D./) {
	    push @cpp, $_;
	} elsif (/^-I./) {
	    push @cpp, $_;
	} elsif ($_ eq '-o') {
	    push @cc, $_, shift;
	} elsif ($_ eq '-c') {
	    $linking = 0;
	    push @cc, $_;
	} else {
	    push @cc, $_;
	}
    } elsif (/(.*)\.c$/) {
	push @source, $1;
	my $base = basename $1;
	push @cc, '-o', "$base.o", "$base.inst.c";
    } elsif (/\.([ao]|so)$/) {
	push @cc, $_;
    } else {
	die "unrecognized command-line option: $_\n";
    }
}


foreach (@source) {
    my $base = basename $_;
    warn "mangling $base\n";
    sys @cpp, '-o', "$base.i", '-E', "$_.c";
    sys "$FindBin::Bin/main $base.i >$base.inst.c";
    die unless -s "$base.inst.c";
}


push @cc, "$FindBin::Bin/liblog/liblog.a" if $linking;
sys @cc;
