#include <Bonobo.idl>

module Sampler {
//   typedef unsigned long long signature[2];
//   typedef sequence <unsigned long> counts;
  
  interface Uploader : Bonobo::Unknown {
    oneway void increment();
    oneway void decrement();
//     oneway void reportUnit(in signature signature, in counts counts);
//     oneway void exitStatus(in octet status);
//     oneway void exitSignal(in octet signal);
  };
};
