Import('env')
env.Tool('literal')
File('literal.py')

entity = '<!ENTITY prefix "$prefix">'
config = env.Literal('config.xml', entity)
Default(config)

Alias('install', env.Install('$DESTDIR$docdir', config))

SConscript(dirs=['sampler-guide/C'])
