#!/usr/bin/python -O

import os.path        
import sys
sys.path.append('../common')

import Paths
Paths.glade = 'wrapper.glade'

from ServerMessage import ServerMessage

dialog = ServerMessage('http://www.cs.berkeley.edu/', 'text/html', '<html><head></head><body><p>Hello <img src="http://www.cs.berkeley.edu/icons/balls/redball.gif"/><img src="http://www.cs.berkeley.edu/icons/balls/redball.gif"/><img src="http://www.cs.berkeley.edu/icons/balls/greenball.gif"/> world!</p></body></html>')
dialog.run()
