Import('env', 'testPythons')
env = env.Copy(first_timedir=env.subst('$first_timedir'))

Default(env.Template('Paths.py.in', varlist=['first_timedir']))
pythons = ['FirstTime.py', 'Main.py']

pythons.append('Paths.py')
compiled = env.PythonBytecodeOpt(pythons)

glade = env.Template('first-time.glade.in', varlist=['deployment_learn_more_url'])
script = env.Template('first-time.in', varlist=['commondir', 'first_timedir'])
Default([glade, script])

testPythons(env, pythons)
Alias('test', env.TestXML(glade))

Alias('install', env.Install('$DESTDIR$first_timedir', [compiled, glade, script]))
