#!/usr/bin/python -O

import os.path        
import sys
sys.path.append('../common')

import Paths
Paths.ui = 'wrapper.ui'

from os.path import dirname, realpath
import SamplerConfig
SamplerConfig.pixmapsdir = dirname(realpath(sys.argv[0])) + '/../pixmaps'

from ServerMessage import ServerMessage

page = open('test-message.html').read()
dialog = ServerMessage('http://www.cs.wisc.edu/', 'text/html', page)
dialog.run()
