#!/usr/bin/python

import dbus

bus = dbus.SessionBus()
remote = bus.get_object('edu.wisc.cs.cbi.FirstTime', '/edu/wisc/cs/cbi/FirstTime')
iface = dbus.Interface(remote, 'edu.wisc.cs.cbi.FirstTime')
iface.present()
