#!/usr/bin/perl -w

use strict;
use Miner;
use FileHandle;


local ($,, $\) = ("\t", "\n");

my $summary = new FileHandle 'site-info.dat', 'w';
$summary->print('file', 'line', 'func', 'left', 'right', 'id');

my $trace = Miner::readTrace($ARGV[0]);
while (<$trace>) {
    my @F = split /\t/;
    $summary->print(@F[0 .. 5]);
}
