#!/usr/bin/perl -w

use strict;
use Miner;
use FileHandle;


local ($,, $\) = ("\t", "\n");

open STDOUT, '>summary.dat';
print 'less', 'equal', 'greater';

foreach my $seed ($ARGV[0] .. $ARGV[1]) {
    warn "reading trace $seed...\n";

    # cut appears to work significantly faster than doing the same
    # slicing within Perl.

    my $traceName = Miner::traceName($seed);
    system("zcat $traceName | cut -d '\t' -f 7-9") == 0
	or die;
}
