#!/usr/bin/perl -w

use strict;
use FileHandle;


die unless @ARGV == 2;
my ($siteNum, $numSites) = @ARGV;

# We could do this all in Perl, but sed appears to be significantly
# faster.

exec ('sed', '-n',
      '-e', '1p',
      '-e', $siteNum + 1 . "~${numSites}p");
die;
