#include <Bonobo.idl>


module Sampler {
  interface ReportCollector : Bonobo::Unknown {
    oneway void addHeader(in string name, in string value);
    oneway void addReport(in string name, in string contents);
    oneway void submit(in string url);
  };
};
