Import('env', 'testPythons')
env = env.Copy(bindir=env.subst('$bindir'),
               traydir=env.subst('$traydir'))

service = env.Template('edu.wisc.cs.cbi.Monitor.service.in', varlist=['traydir'])
Default([service, env.Template('Paths.py.in', varlist=['bindir', 'traydir'])])

pythons = ['AboutDialog.py', 'Main.py', 'PopupMenu.py', 'PreferencesDialog.py', 'Service.py', 'TrayIcon.py']

pythons.append('Paths.py')
compiled = env.PythonBytecodeOpt(pythons)

testPythons(env, pythons)
Alias('test', [
    env.TestXML('oaf.dtd'),
    env.TestXML('tray.glade'),
    ])

Alias('install', [
    env.Install('$DESTDIR$servicesdir', service),
    env.Install('$DESTDIR$traydir', [compiled, 'tray.glade']),
    ])
