Import('env', 'testPythons')
env = env.Clone(bindir=env.subst('$bindir'),
               traydir=env.subst('$traydir'))

service = env.Template('edu.wisc.cs.cbi.Monitor.service.in', varlist=['traydir'])
Default(service)

pythons = [
    'AboutBoxIcon.py',
    'Main.py',
    'Service.py',
    'TrayIcon.py',
    ]

compiled = env.PythonBytecodeOpt(pythons)
Default(compiled)
testPythons(env, pythons)

ui = 'tray.ui'
Alias('test', [
        env.TestXML(ui, schema=File('../gtk-builder.xsd')),
        ])

Alias('install', [
    env.Install('$DESTDIR$servicesdir', service),
    env.Install('$DESTDIR$traydir', [compiled, 'tray', ui]),
    ])
