#!/usr/bin/python

from gi.repository import Gio

from contextlib import contextmanager
from sys import stdout
from time import sleep

@contextmanager
def verbosely(description):
    print description, '...',
    stdout.flush()
    yield
    print 'done'

with verbosely('initializing'):
    bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
    tray = Gio.DBusProxy.new_sync(bus, 0, None, 'edu.wisc.cs.cbi.Monitor', '/edu/wisc/cs/cbi/Monitor', 'edu.wisc.cs.cbi.Monitor', None)

with verbosely('activating'):
    tray.activate()

with verbosely('sleeping for five seconds'):
    sleep(5)
