#!/usr/bin/python

from os import environ
from os.path import dirname, realpath
from sys import argv, path

home = realpath(dirname(argv[0]))
environ['XDG_DATA_DIRS'] = ':'.join([
    home + '/..',
    '/usr/local/share',
    '/usr/share',
    ])

import Paths
Paths.home = home
Paths.ui = home + '/tray.ui'

path.append(realpath(home + '/../common'))

import SamplerConfig
SamplerConfig.pixmapsdir = realpath(home + '/../pixmaps')

import Main
Main.main()
