########################################################################


Import('env')
env = env.Clone()
env.AppendUnique(CC=['--sampler-scheme=function-entries'])

fenv = env.Clone()
fenv.AppendUnique(CC=['--timestamp-first'])

lenv = env.Clone()
lenv.AppendUnique(CC=['--timestamp-last'])

benv = env.Clone()
benv.AppendUnique(CC=['--timestamp-first', '--timestamp-last'])
benv.Command('both.expected', ['first.expected', 'last.expected'], [['cat', '$SOURCES', '>$TARGET']])

tests = [(fenv, 'first'), (lenv, 'last'), (benv, 'both')]
tests = [ env.CBIResolvedTimestamps(env.CBIStaticObject('%s.o' % base, 'simple.c'), objects=base) for env, base in tests ]

Alias('test:returns', map(env.Expect, tests))
Alias('test', 'test:returns')

File(Glob('*.expected'))
