Import('env')
env = env.Clone()
env.AppendUnique(CC=['-fsampler-scheme=bounds'], CCFLAGS=['-fassign-across-pointer'])

enum = env.CBIProgram('enum.c')

Alias('test:bounds', env.Expect([
    env.CBIResolvedSamples(env.CBIReports(enum), objects=enum),
    ]))

Alias('test', 'test:bounds')

File(Glob('*.expected'))
