Import('env')


cc1 = env.Template('cc1.in', varlist=['gcc'])
cc = env.Template('sampler-cc.in', varlist=['driverdir', 'gcc'])
here = env.Template('sampler-cc-here.in', varlist=['gcc'])

key = 'cpp_tuple_counter_bits_default'
if env['tuple_counter_bits'] == 'natural':
    env[key] = ''
else:
    env[key] = '-DCBI_TUPLE_COUNTER_BITS=$tuple_counter_bits'
specs = env.Template('sampler-specs.in', varlist=[key])

Default('.')


Alias('install', [
    env.Install('$DESTDIR$bindir', cc),
    env.Install('$DESTDIR$driverdir', ['as', cc1, 'sampler-specs']),
    ])
