Import('env', 'threadLibs')

env = env.Copy()
threadLibs(env, 'no')

precompute = env.Program(['precompute.c', '${LIBPREFIX}sampler-online${LIBSUFFIX}', '${LIBPREFIX}sampler${LIBSUFFIX}'])
Default(precompute)

env.Append(ENV={'SAMPLER_SPARSITY': '1'})
env.Command('countdown-1-1', precompute, [['$SOURCES', '$TARGET']])

Alias('install', env.Install('$DESTDIR$toolsdir', precompute))


Import('dist')
dist('precompute.c')
