#!/usr/bin/python -O

import sys

import pygtk
pygtk.require('2.0')

import bonobo
import gconf
import gnome

from AppFinder import AppFinder
from AppModel import AppModel
from Application import Application
from Factory import Factory
from GConfDir import GConfDir
from UploaderTrayIcon import UploaderTrayIcon

import Config
import Keys


# !!!: begin temporary hack zone
import os, sys
#sys.stdout = sys.stderr = file('/dev/pts/2', 'w')
os.chdir(os.path.dirname(sys.argv[0]))
# !!!: end temporary hack zone


gnome.program_init('sampler', Config.version)

client = gconf.client_get_default()
dir = GConfDir(client, Keys.root, gconf.CLIENT_PRELOAD_NONE)

factory = Factory()

finder = AppFinder()
model = AppModel()
for path in finder:
    app = Application(client, model, path)

tray = UploaderTrayIcon(client, model)
tray.show_all()

bonobo.main()
sys.exit(bonobo.debug_shutdown())
