Import('env', 'threadLibs')

env = env.Clone()
threadLibs(env, 'no')

sources = map(env.File, ['precompute.c', '${LIBPREFIX}sampler-online${LIBSUFFIX}', '${LIBPREFIX}sampler${LIBSUFFIX}'])
precompute = env.Program(sources)
Default(precompute)

Alias('install', env.Install('$DESTDIR$toolsdir', precompute))
