Import('env')
env.Tool('literal', toolpath=['#scons-tools'])
env.File('#scons-tools/literal.py')

entity = '<!ENTITY prefix "$prefix">'
config = env.Literal('config.dtd', entity)
Default(config)

Alias('install', env.Install('$DESTDIR$docdir', config))

SConscript(dirs=['sampler-guide/C'])
