Import('env', 'threadLibs')

env = env.Clone()
env.AppendUnique(
    CPPDEFINES='CBI_THREADS',
    CCFLAGS=['-pthread'],
    LINKFLAGS=['-Wl,--wrap,pthread_create'],
    REENTRANT='_r',
    )

threadLibs(env, 'yes')
