#!/usr/bin/perl -w

use strict;
use FindBin;


########################################################################


sub trace_system (@) {
    my $error = system @_;

    if ($error == -1) {
	die "cannot run $_[0]: $!\n";
    } elsif ($error) {
	my $result = $error >> 8 || $error & 127 || -1;
	exit $result;
    }
}


########################################################################


my $dir = $FindBin::Bin;
my $liblog = "$dir/liblog";

push @ARGV, '-include', "$liblog/log.h";
push @ARGV, '-Wno-uninitialized';
push @ARGV, "-Wl,-rpath,$liblog", "-L$liblog", '-llog'
    unless grep /^-[cE]$/, @ARGV;

trace_system "$dir/../front-end", "$dir/main", @ARGV;
