Import('env', 'testPythons')
env = env.Copy(bindir=env.subst('$bindir'),
               traydir=env.subst('$traydir'))

server = env.Template('Sampler_Monitor.server.in', varlist=['traydir'])
Default([server, env.Template('Paths.py.in', varlist=['bindir', 'traydir'])])

pythons = ['AboutDialog.py', 'BusyCursor.py', 'Factory.py', 'LazyDialog.py', 'LazyWidget.py', 'Main.py', 'PopupMenu.py', 'PreferencesDialog.py', 'UploaderTrayIcon.py']

Import('dist')
dist(['SConscript', pythons])

pythons.append('Paths.py')
compiled = env.PythonBytecodeOpt(pythons)

testPythons(env, pythons)
Alias('test', [
    env.TestXML([server, 'oaf.dtd']),
    env.TestXML('tray.glade'),
    ])

Alias('install', [
    env.Install('$DESTDIR$serversdir', server),
    env.Install('$DESTDIR$traydir', [compiled, 'tray.glade']),
    ])
