#!/usr/bin/perl -w

use strict;
use FindBin;
use lib $FindBin::Bin;
use lib "$FindBin::Bin/../../driver";
use lib "$FindBin::Bin/../../../../cil/bin";
use lib "$FindBin::Bin/../../../../cil/lib";

use Nothing;
Nothing->new(@ARGV)->doit();
