Import('env')

env = env.Clone(tools=['libraries'], toolpath='.')
env.AppendUnique(
    CCFLAGS=['-O'],
    )
env.File('libraries.py')

tenv = env.Clone(
    CCFLAGS=['-O', '-fPIC'],
    CPPPATH=['.', '$HOME/.local/include'],
    LIBPATH=['$HOME/.local/lib'],
    LIBS=['dl', 'lttng-ust'],
)
libtrace = tenv.StaticLibrary('#driver/trace', tenv.StaticObject('trace.o', 'trace.c'))
Alias('install', tenv.Install('$DESTDIR$libdir', libtrace))

headers = [
    'blast-markers.h',
    'registry.h',
    'report.h',
    'signature.h',
    'timestamps.h',
    'trace-lttng.h',
    'trace.h',
    'unit-signature.h',
    'unit.h',
    ]

Install('#driver/sampler', headers)
Alias('install', env.Install('$DESTDIR$samplerdir', headers))

SConscript(dirs=['schemes', 'threads'], exports=['env'])
