#!/bin/sh -ex

host=sampler.cs.berkeley.edu
if ssh $host 'mv /var/www/sampler-uploads/* /var/www/sampler-transfer'; then
  rsync -rlto -v --compare-dest=/afs/cs.wisc.edu/p/cbi/uploads/archive "$@" $host:/var/www/sampler-transfer/ /afs/cs.wisc.edu/p/cbi/uploads/reports
  ssh $host 'mv /var/www/sampler-transfer/* /var/www/sampler-archive'
fi
