Import('env')
env = env.Copy()
env.AppendUnique(CCFLAGS=['-fpic'])

genv = env.Copy()
genv.ParseConfig('$pkg_config --cflags --libs glib-2.0')
gobjs = genv.StaticObject(source=['g-object-unref.c', 'g-object-unref-classify.c'])

lib = env.Library('libschemes.a', [
    gobjs,
    'bounds.c',
    'branches.c',
    'float-kinds.c',
    'function-entries.c',
    'returns.c',
    'samples.c',
    'scalar-pairs.c',
    'timestamps.c',
    'tuple-1.c',
    'tuple-2.c',
    'tuple-3.c',
    'tuple-4.c',
    'tuple-9.c',
    ])

Default(lib)

Alias('install', env.Install('$DESTDIR$schemesdir', [
    lib,
    'bounds-unit.h',
    'bounds.h',
    'branches-unit.h',
    'branches.h',
    'float-kinds-unit.h',
    'float-kinds.h',
    'function-entries-unit.h',
    'function-entries.h',
    'g-object-unref-unit.h',
    'g-object-unref.h',
    'returns-unit.h',
    'returns.h',
    'scalar-pairs-unit.h',
    'scalar-pairs.h',
    'tuple-1.h',
    'tuple-2.h',
    'tuple-3.h',
    'tuple-4.h',
    'tuple-9.h',
    ]))
