#!/usr/bin/perl -w

use strict;


die "Usage: $0 <scheme>\n" unless @ARGV == 1;
my $scheme = shift;


while (my $signature = <STDIN>) {
    chomp $signature;
    print "<samples unit=\"$signature\" scheme=\"$scheme\">\n";

    while (my $tuple = <STDIN>) {
	last if $tuple eq "\n";
	print $tuple;
    }

    print "</samples>\n";
}
