Import('env')
env = env.Clone()
env.AppendUnique(CC=['--sampler-scheme=g-object-unref'])
env.ParseConfig(['$pkg_config', '--cflags', '--libs', 'gobject-2.0'])

test = env.CBIProgram('test.c')

Alias('test:g-object-unref', env.Expect([
    env.CBIResolvedSamples(env.CBIReports(test, TEST_STDERR='/dev/null'), objects=test),
    ]))

Alias('test', 'test:g-object-unref')
