from utils import instantiate

Import('env', 'testPythons')
env = env.Copy(pixmapsdir=env.subst('$pixmapsdir'))

Default(env.Template('SamplerConfig.py.in', varlist=['VERSION', 'pixmapsdir']))
pythons = ['BlipIcons.py', 'GConfDir.py', 'GConfNotifier.py', 'Keys.py', 'MasterNotifier.py', 'Signals.py', 'WindowIcon.py']

pythons.append('SamplerConfig.py')
compiled = env.PythonBytecodeOpt(pythons)

testPythons(env, pythons)

Alias('install', env.Install('$DESTDIR$commondir', compiled))
