Import('env', 'testPythons')

Default(env.Template('SamplerConfig.py.in', varlist=['VERSION']))
pythons = [
    'EnabledIcon.py',
    'Keys.py',
    'SamplerConfig.py',
    'WindowIcon.py',
    ]

compiled = env.PythonBytecodeOpt(pythons)
Default(compiled)

testPythons(env, pythons)

Alias('install', env.Install('$DESTDIR$commondir', compiled))
