from utils import extra_build_dirs
Import('env')

env = env.Copy()
env.AppendUnique(OCAML_PATH=extra_build_dirs(env, ['ocaml']))

env.OcamlObject([
    'fixpoint.ml',
    'fixpoint.mli',
    'hashClass.ml',
    'hashClass.mli',
    'queueClass.ml',
    'queueClass.mli',
    'stackClass.ml',
    'stackClass.mli',
    'stringHash.ml',
    'stringHash.mli',
    ])
