/* Generated by CIL v. 1.0 */

//# 12 "test.c"
struct Node {
   double value ;
   struct Node *next ;
};
//# 12
typedef struct Node Node;
//# 7
struct Multinode {
   int count ;
   Node node ;
};
//# 7
typedef struct Multinode Multinode;
//# 5 "/var/local/liblit/ocaml/sampler/assignments/liblog/log.h"
extern void ( /* format attribute */  logVars)(char const   *  , ...) ;
//# 5 "/var/local/liblit/ocaml/sampler/libcountdown/countdown.h"
extern unsigned int nextLogCountdown ;
//# 13 "test.c"
int main(void) 
{ int x ;
  Node a ;
  Multinode b ;
  unsigned int localCountdown5 ;

  {
  localCountdown5 = nextLogCountdown;
  if (localCountdown5 > 6U) {
    {
    {
//# 15
    x = 7;
//# 15
    localCountdown5 --;
    }
    {
//# 16
    a.value = 3.14;
//# 16
    localCountdown5 --;
    }
    {
//# 16
    a.next = (struct Node *)0;
//# 16
    localCountdown5 --;
    }
    {
//# 17
    b.count = x;
//# 17
    localCountdown5 --;
    }
    {
//# 17
    b.node = a;
//# 17
    localCountdown5 --;
    }
    {
//# 18
    b.node.next = & a;
//# 18
    localCountdown5 --;
    }
    }
    {
//# 20
    nextLogCountdown = localCountdown5;
//# 20
    return (0);
    }
  } else {
    {
    {
//# 15
    x = 7;
//# 15
    nextLogCountdown = localCountdown5;
//# 15
    logVars("%s:%u:\n\tx <- %d\n", "test.c", 15U, x);
//# 15
    localCountdown5 = nextLogCountdown;
    }
    {
//# 16
    a.value = 3.14;
//# 16
    nextLogCountdown = localCountdown5;
//# 16
    logVars("%s:%u:\n\ta.value <- %g\n", "test.c", 16U, a.value);
//# 16
    localCountdown5 = nextLogCountdown;
    }
    {
//# 16
    a.next = (struct Node *)0;
//# 16
    nextLogCountdown = localCountdown5;
//# 16
    logVars("%s:%u:\n\ta.next <- %p\n", "test.c", 16U, a.next);
//# 16
    localCountdown5 = nextLogCountdown;
    }
    {
//# 17
    b.count = x;
//# 17
    nextLogCountdown = localCountdown5;
//# 17
    logVars("%s:%u:\n\tb.count <- %d\n", "test.c", 17U, b.count);
//# 17
    localCountdown5 = nextLogCountdown;
    }
    {
//# 17
    b.node = a;
//# 17
    nextLogCountdown = localCountdown5;
//# 17
    logVars("%s:%u:\n\tb.node.value <- %g\n\tb.node.next <- %p\n", "test.c", 17U,
            b.node.value, b.node.next);
//# 17
    localCountdown5 = nextLogCountdown;
    }
    {
//# 18
    b.node.next = & a;
//# 18
    nextLogCountdown = localCountdown5;
//# 18
    logVars("%s:%u:\n\tb.node.next <- %p\n", "test.c", 18U, b.node.next);
//# 18
    localCountdown5 = nextLogCountdown;
    }
    }
    {
//# 20
    nextLogCountdown = localCountdown5;
//# 20
    return (0);
    }
  }
}
}
