#!/usr/bin/python

import dbus
from time import sleep

bus = dbus.SessionBus()
remote = bus.get_object('edu.wisc.cs.cbi.Monitor', '/edu/wisc/cs/cbi/Monitor')
iface = dbus.Interface(remote, 'edu.wisc.cs.cbi.Monitor')
iface.activate()
sleep(5)
