Import('env')
env.AppendUnique(CCFLAGS='-Wno-attributes')

penv = env.Clone()
penv.AppendUnique(CC=['-pipe'])

File('library.h')
File(Glob('*.expected'))

senv = env.Clone(SHLIBPREFIX='')
plugin = senv.CBISharedLibrary('libplugin.so', 'plugin.c')
library = senv.CBISharedLibrary('library.c')
main = senv.CBIProgram(['main.c', library], LIBS='dl')

Alias('test:nothing', [
    penv.CBIResolvedCFG('pipes.c', objects='pipes'),
    env.CBIStaticObject('last-switch.c'),
    env.Expect(env.CBIResolvedCFG('cfg.c', objects='cfg')),
    senv.CBIReports([main, plugin]),
    ])

Alias('test', 'test:nothing')
