Import('env')
env = env.Clone()
env.AppendUnique(CC=['--sampler-scheme=function-entries'])

test = env.CBIProgram('test.c')

Alias('test:function-entries', env.Expect([
    env.CBIResolvedSamples(env.CBIReports(test), objects=test),
    ]))

Alias('test', 'test:function-entries')
