Import('env')
env = env.Copy()
env.AppendUnique(CCFLAGS=['--balance-paths', '--sampler-scheme=returns'])

Alias('test:balance', map(env.CBIStaticObject, [
    'default.c',
    'goto-bottom.c',
    'goto-middle.c',
    'goto-top-post.c',
    'goto-top-pre.c',
    'if-both.c',
    'if-else.c',
    'if-then.c',
    'no-default.c',
    'switch-if.c',
    'loop-if.c',
    ]))

Alias('test', 'test:balance')
