#!/usr/bin/python -O

from sys import argv, stderr, stdin


def main():
    if len(argv) != 2:
        print >>stderr, 'Usage; %s <report-id>' % argv[0]
        exit(2)

    found = False
    [target] = argv[1:]
    report_begin = '<report id="%s">\n' % target
    report_end = '</report>\n'

    for line in stdin:
        if line == report_begin:
            found = True
            for line in stdin:
                if line == report_end:
                    break
                print line,

    exit(not found)


if __name__ == '__main__':
    main()
