#!/usr/bin/perl -w

use strict;
use 5.008;			# for safe pipe opens using list form of open

use Fcntl qw(SEEK_SET);
use FileHandle;
use FindBin;

use lib $FindBin::Bin;
use RawSamples;
use SiteInfo;


########################################################################


my $siteInfo = new SiteInfo;
$siteInfo->load($_) foreach @ARGV;

my $rawSamples = new RawSamples;
$rawSamples->read(\*STDIN);


sub dump ($$@) {
    my ($unit, $scheme, @tuples) = @_;
    my @sites = $siteInfo->find($unit, $scheme);

    @tuples == @sites
	or die "mismatched count of samples and sites for unit $unit, scheme $scheme\n";

    local ($,, $\) = ("\t", "\n");
    foreach (0 .. $#tuples) {
	print $unit, $scheme, $sites[$_], $tuples[$_];
    }
}

$rawSamples->foreach(\&dump);
