Import('env', 'testPythons')
env = env.Clone(first_timedir=env.subst('$first_timedir'))

Default(env.Template('Paths.py.in', varlist=['first_timedir']))
pythons = ['FirstTime.py', 'Main.py', 'Service.py', 'StatusIcon.py']

pythons.append('Paths.py')
compiled = env.PythonBytecodeOpt(pythons)
Default(compiled)

ui = env.Template('first-time.ui.in', varlist=['deployment_learn_more_url'])
script = env.Template('first-time.in', varlist=['commondir', 'first_timedir'])
service = env.Template('edu.wisc.cs.cbi.FirstTime.service.in', varlist=['first_timedir'])
Default([ui, script, service])

testPythons(env, pythons)
Alias('test', env.TestXML(ui, schema=File('../gtk-builder.xsd')))

Alias('install', [
    env.Install('$DESTDIR$first_timedir', [compiled, ui, script]),
    env.Install('$DESTDIR$servicesdir', service),
    ])
