top := ..
include $(top)/defs.mk

targets := driver.$(cma)

include $(top)/rules.mk


########################################################################


driver.$(cma):
driver.$(cma): $(instDriver)
	$(archive)
