Import('env', 'testPythons')
env = env.Copy(commondir=env.subst('$commondir'),
               first_timedir=env.subst('$first_timedir'),
               wrapperdir=env.subst('$wrapperdir'))

Default(env.Template('Paths.py.in', varlist=['commondir', 'first_timedir', 'wrapperdir']))
pythons = ['AppConfig.py', 'Launcher.py', 'Main2.py', 'Main.py', 'Outcome.py', 'RedirectHandler.py', 'ReportsReader.py', 'SampledLauncher.py', 'ServerMessage.py', 'UnsampledLauncher.py', 'Uploader.py', 'Upload.py', 'UserConfig.py']

pythons.append('Paths.py')
compiled = env.PythonBytecodeOpt(pythons)

testPythons(env, pythons)
Alias('test', env.TestXML('wrapper.glade'))

Alias('install', env.Install('$DESTDIR$wrapperdir', [compiled, 'wrapper.glade']))
