#!/usr/bin/python

from os import environ
from os.path import abspath, dirname

home = dirname(abspath(__file__))
launcher = dirname(home)
environ['XDG_DATA_DIRS'] = ':'.join([
    launcher,
    '/usr/local/share',
    '/usr/share',
    ])

import Main2
Main2.main(name = 'test-in-place',
           wrapped = '/usr/lib/sampler/wrapped/usr/bin/pidgin',
           upload_headers = {}
           )
