#!/usr/bin/perl -wT

use strict;

use CGI qw(:standard -private_tempfiles);
use CGI::Carp qw(fatalsToBrowser);

use lib '/usr/lib/perl5/site_perl/5.6.1';
use DB_File::Lock;
use POSIX qw(S_IRUSR S_IWUSR);


########################################################################


my $query = new CGI;

my $remote = $query->remote_host;
my $distro = param('distro');
die "survey returned with no answer\n" unless defined $distro;


my %survey;
tie %survey, 'DB_File::Lock', '/var/www/sampler-survey/distro.db',
    O_CREAT | O_RDWR, S_IRUSR | S_IWUSR, $DB_HASH, 'write';

$survey{$remote} = $distro;

untie %survey;


print($query->redirect('http://www.cs.berkeley.edu/~liblit/sampler/survey/thanks.html'));
