#!/usr/bin/python -O

from os import walk
from sys import stderr

def main():
    for root, dirs, files in walk('.'):
        for impl in files:
            if impl.endswith('.ml'):
                iface = impl + 'i'
                if not iface in files:
                    print >>stderr, 'implicit interface: %s/%s' % (root, impl)

if __name__ == '__main__':
    main()
