tests := 					\
	array					\
	bumpy					\
	conditional				\
	deep-pointers				\
	funcall					\
	loop					\
	multiple				\
	return					\
	sizeof					\
	structures				\
	tiny

funcall: LOADLIBES := -lm

include ../../tests.mk
