from utils import extra_build_dirs
Import('env')

env = env.Copy(OCAML_LIBS=['unix'])
env.AppendUnique(OCAML_PATH=extra_build_dirs(env, ['ocaml', 'tools/cfg/graphlib']))

env.OcamlObject([
    'graph.ml',
    'graph.mli',
    'task.mli',
    'transitive.ml',
    'transitive.mli',
    ])
