Import('env')
env = env.Copy()
env.AppendUnique(CC=['--sampler-scheme=bounds'], CCFLAGS=['--assign-across-pointer'])

enum = env.CBIProgram('enum.c')

Alias('test:bounds', env.Expect([
    env.CBIResolvedSamples(env.CBIReports(enum), objects=enum),
    ]))

Alias('test', 'test:bounds')
