#!/usr/bin/perl -w

use strict;
use File::Basename;
use FileHandle;


my $master;
my %packages;


sub subflatten ($$$) {
    my ($space, $name, $suffix) = @_;
    my $path = `kpsewhich $name.$suffix`;
    if ($path =~ /^\/usr\//) {
	print $_;
    } else {
	chomp $path;
	print STDERR "including external file: $path\n";
	print "$space%% begin external file: $_";
	flatten($path);
	print "$space%% end external file: $_";
    }
}


sub flatten ($) {
    my $name = shift;
    my $handle = new FileHandle $name or die;
    while (local $_ = $handle->getline) {
	if (/^(\s*)\\usepackage{(.*)}$/) {
	    unless (exists $packages{$2}) {
		$packages{$2} = 1;
		subflatten $1, $2, 'sty';
	    }
	} elsif (/^(\s*)\\input{(.*)}$/) {
	    subflatten $1, $2, 'tex';
	} elsif (/^(\s*)\\bibliography{.*}$/) {
	    subflatten $1, $master, 'bbl';
	} else {
	    print $_;
	}
    }
}


foreach (@ARGV) {
    $master = basename $_, '.tex';
    flatten $_;
}
