#!/usr/bin/python -O

import os.path        
import sys
sys.path.append('../common')

import Paths
Paths.glade = 'wrapper.glade'

from ServerMessage import ServerMessage

dialog = ServerMessage('http://www.cs.wisc.edu/', 'text/html', '<html><head></head><body><p>Hello <img src="http://www.cs.wisc.edu/icons/ball.red.gif"/><img src="http://www.cs.wisc.edu/icons/ball.red.gif"/><img src="http://www.cs.wisc.edu/icons/ball.gray.gif"/> world!</p></body></html>')
dialog.run()
