/* Generated by CIL v. 1.0.1 */
/* print_CIL_Input is false */

# 5 "/var/local/liblit/ocaml/sampler/instrumentor/decure/driver/../libdecure/decure.h"
extern unsigned int resetCountdown()  __attribute__((__alias__("getNextCountdown"))) ;
# 5 "/var/local/liblit/ocaml/sampler/instrumentor/decure/driver/../../../libcountdown/countdown.h"
extern unsigned int nextEventCountdown ;
# 8 "/var/local/liblit/ocaml/cil/include/ccured.h"
extern int __ccuredWarnOnFail ;
# 12
extern int __ccuredUseStrings ;
# 15
extern int __ccuredLogNonPointers ;
# 164 "/var/local/liblit/ocaml/cil/include/fp_fail.h"
extern void fp_fail(int msgId , char *file , int line )  __attribute__((__noreturn__)) ;
# 578 "/var/local/liblit/ocaml/cil/include/ccuredcheck.h"
__inline static void __CHECK_NULL(void *p , char *file , int line ) 
{ 

  {
# 581
  if (! p) {
    {
# 584
    fp_fail(6, file, line);

    }
  }
# 581
  return;
}
}
# 160 "crasher.c"
extern void ccuredInit(void) ;
# 160
int main(void) ;
# 160 "crasher.c"
int main(void) 
{ int *nothing ;
  int __retres ;
  unsigned int localCountdown3 ;

  {
  localCountdown3 = nextEventCountdown;
  {
  {
# 160
  nothing = (int *)0;
# 160
  __ccuredWarnOnFail = 0;
# 160
  __ccuredUseStrings = 0;
# 160
  __ccuredLogNonPointers = 0;
  {
# 160
  nextEventCountdown = localCountdown3;
# 160
  ccuredInit();
# 160
  localCountdown3 = nextEventCountdown;
  {
  if (__builtin_expect(localCountdown3 > 1U, 1)) {
    goto postCall1;
  } else {
    goto postCall1__dup;
  }
  postCall1: /* CIL Label */ ;
  }
  }
# 3
  nothing = (int *)0;
  {
# 4
  localCountdown3 --;

  }
# 4
  __retres = (*nothing);
  }
  {
# 160
  nextEventCountdown = localCountdown3;
# 160
  return (__retres);
  }
  }
  goto finis;
  {
  {
# 160
  nothing = (int *)0;
# 160
  __ccuredWarnOnFail = 0;
# 160
  __ccuredUseStrings = 0;
# 160
  __ccuredLogNonPointers = 0;
  {
# 160
  nextEventCountdown = localCountdown3;
# 160
  ccuredInit();
# 160
  localCountdown3 = nextEventCountdown;
  {
  if (__builtin_expect(localCountdown3 > 1U, 1)) {
    goto postCall1;
  } else {
    goto postCall1__dup;
  }
  postCall1__dup: /* CIL Label */ ;
  }
  }
# 3
  nothing = (int *)0;
  {
  {
# 4
  localCountdown3 --;
# 4
  if (localCountdown3 == 0) {
# 4
    nextEventCountdown = localCountdown3;
# 4
    __CHECK_NULL((void *)nothing, "crasher.c:main", 4);
# 4
    localCountdown3 = nextEventCountdown;
# 4
    localCountdown3 = resetCountdown();
  }
  }

  }
# 4
  __retres = (*nothing);
  }
  {
# 160
  nextEventCountdown = localCountdown3;
# 160
  return (__retres);
  }
  }
  finis: /* CIL Label */ ;
}
}
