Import('env', 'testPythons')
env = env.Copy(preferencesdir=env.subst('$preferencesdir'))

Default(env.Template('Paths.py.in', varlist=['preferencesdir']))
pythons = ['AppFinder.py', 'Application.py', 'AppModel.py', 'Main.py', 'Paths.py', 'PreferencesDialog.py']

testPythons(env, pythons)
Alias('test', env.TestDesktop('sampler-preferences.desktop'))
