from glob import glob

SConscript(dirs='graphlib')

Import('env')
env = env.Copy(OCAML_LIBS=['unix'], OCAML_PP='camlp4o.opt')
env.AppendUnique(OCAML_PATH=['ocaml', 'tools/cfg', 'tools/cfg/graphlib'])

sources = glob('*.ml') + glob('*.mli')
sources.remove('basics.ml')
sources.remove('dotty.ml')
sources.remove('dotty.mli')

wenv = env.Copy(OCAML_WARN='Ae')
basics = wenv.OcamlObject('basics.ml')

env.OcamlObject(sources)
Default(env.OcamlProgram('order-sites.ml'),
        env.OcamlProgram('resolve-cfg.ml'))
